apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
  labels:
    app: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kubernetes Administrator Course</title>
    </head>
    <body>
        <h1>This is Josh, trainer of Kubernetes Administrator course</h1>
        <p>You must read three chapters before starting the practical part of the course.</p>
    </body>
    </html>
    
# This ConfigMap contains the static content in an HTML file called index.html.
